#pragma once
#include <string>

// The piece themes, without any graphics dependency (so the unit tests cover the name table). A theme is the
// asset-id prefix of its textures ("piece.pixel." + "white_pawn"), plus whether it ships eyes-closed blink frames
// ("piece.pixel.white_pawn_blink"). All themes are original, generated by scripts/gen_<id>_theme.py.
struct PieceTheme {
  const char* prefix;
  bool hasBlink;
};

namespace Themes {
inline constexpr PieceTheme pixel{"piece.pixel.", true};        // original pixel-art creatures (the default)
inline constexpr PieceTheme medieval{"piece.medieval.", false}; // heraldic ivory and walnut pieces
inline constexpr PieceTheme bauhaus{"piece.bauhaus.", false};   // flat geometric primary-colour pieces
inline constexpr PieceTheme neon{"piece.neon.", false};         // glowing line-art pieces
inline constexpr PieceTheme origami{"piece.origami.", false};   // folded-paper pieces
inline constexpr PieceTheme ink{"piece.ink.", false};           // brush-ink pieces

// The one table behind byName, nameOf and the Settings labels: Settings / theme_preview name -> theme, in
// Settings-screen order. The first entry is the default (and nameOf's fallback).
struct Entry {
  const char* name;
  const PieceTheme* theme;
};
inline constexpr Entry all[] = {{"Pixel", &pixel},   {"Medieval", &medieval}, {"Bauhaus", &bauhaus},
                                {"Neon", &neon},     {"Origami", &origami},   {"Ink", &ink}};
inline constexpr int count = static_cast<int>(sizeof(all) / sizeof(all[0]));
// By name; nullptr when unknown (e.g. a theme that an older settings file names but that no longer ships).
const PieceTheme* byName(const std::string& name);
// The name byName() finds the theme by ("Pixel" for an unknown theme).
const char* nameOf(const PieceTheme& theme);
} // namespace Themes
